import { MUNICIPALITY_TYPES } from "./types";

export const MUNICIPALITY_TYPES_OPTIONS: { label: MUNICIPALITY_TYPES; value: MUNICIPALITY_TYPES }[] = [
  { label: MUNICIPALITY_TYPES.SUB_METROPOLITAN_MUNICIPALITY, value: MUNICIPALITY_TYPES.SUB_METROPOLITAN_MUNICIPALITY },
  { label: MUNICIPALITY_TYPES.METROPOLITAN_MUNICIPALITY, value: MUNICIPALITY_TYPES.METROPOLITAN_MUNICIPALITY },
  { label: MUNICIPALITY_TYPES.MUNICIPALITY, value: MUNICIPALITY_TYPES.MUNICIPALITY },
];
